version: '3'
services:
    dev:
        # image: node:12
        build: .
        volumes:
            - .:/usr/src/crawler/
        working_dir: /usr/src/crawler/
        command: bash -c "npm run debug"
        ports:
            - 3000:3000
        depends_on:
            - mongo
        env_file:
            - dev.env

    mongo:
        image: mongo
        expose:
            - "27017"

    mongo-express:
        image: mongo-express
        depends_on: 
            - mongo
        ports:
            - "8081:8081"
